### ISSUE TITLE
Deprecate and remove Claims class

### ISSUE THREAD

**Issue by JeroenDeDauw** [wmde/WikibaseDataModel#157]
The Claims class currently has the highest complexity of this component.

![worst](https://cloud.githubusercontent.com/assets/146040/4007770/0f0384b6-29cb-11e4-9d99-d8167f4bdaa6.jpg)

DataModel 1.0 introduces `ClaimList`, which is a partial alternative. `Entity` and `Item` type hint against this type in several methods.

**Comment by JeroenDeDauw** [comment]
#411 removes a bunch of its methods

**Comment by JeroenDeDauw** [comment]
Looks like the only thing missing before we can ditch the class now is an indexer based on GUIDs, as per #304

**Comment by JeroenDeDauw** [comment]
`Claims::indexOf` still needs a replacement

**Comment by JeroenDeDauw** [comment]
So does `insertClaimAtIndex`

**Comment by JeroenDeDauw** [comment]
Wondering if we can just drop `insertClaimAtIndex` / the second parameter of `addClaim`. Not seeing it used anywhere. Ping @thiemowmde @snaterlicious

**Comment by JeroenDeDauw** [comment]
Looks like everything that was in `Claims` that needed a replacement now has such a replacement. So I'm thinking we can finally ditch the thing.

@thiemowmde anything I'm forgetting about?

**Comment by thiemowmde** [comment]
* The Claims constructor is still called 80 times: 24 times in data-model itself, 18 times in data-model-serialization, 33 times in repo and 4 times in lib.
* `addClaim` is still used in 2 places in repo and data-model-serialization. I would like to prepare a patch[*] for the remaining usage in repo. The serialization component needs a new StatementListDeserializer, which is obvious and could be done later when updating the dependency.
* `hasClaimWithGuid` is still used 2 times in repo and 4 times in repo tests. Replacement is simple: `$statementList->getIndexByGuid( $guid ) !== false`.
* `removeClaimWithGuid` is still used 2 times in repo. There is no simple replacement because StatementList does not support removing statements. This is probably ok but means the 2 remaining usages must be replaced with code that recreates a StatementList or avoids manipulating an existing StatementList at all. I would like to prepare a patch[*] for this before removing the Claims class.
* `getClaimWithGuid` is still used 19 times in repo. Replacement does exist but is not nice:
```php
$statements = $statementList->toArray();
$statement = $statements[$statementList->getIndexByGuid( $guid )];
```
Do you have a better suggestion for that?

[*]2 patches I would like to prepare before ditching the class.

**Comment by thiemowmde** [comment]
The removeClaimWithGuid related patch is done, see https://gerrit.wikimedia.org/r/#/c/204511/. I gave up on addClaim for now. This need a rewrite of ClaimSummaryBuilder.

**Comment by JeroenDeDauw** [comment]
> The Claims constructor is still called 80 times: 24 times in data-model itself, 18 times in data-model-serialization, 33 times in repo and 4 times in lib.

Since StatementList will accept the same arguments as Claims, this ought to not be an issue? Or is there something StatementList does not support and is actually used?

> The serialization component needs a new StatementListDeserializer, which is obvious and could be done later when updating the dependency.

Well yes. I started updating the component in https://github.com/wmde/WikibaseDataModelSerialization/pull/115

> removeClaimWithGuid is still used 2 times in repo. There is no simple replacement because StatementList does not support removing statements.

We have `StatementByGuidMap` now. Which makes sense to use in a situation where building the map pays for itself. If we only need to find a single Statement (be it for retrieval or deletion), then a method that simply goes over all statements is better. In case we have users in that format, we probably should add such methods to StatementList before release.

> $statements = $statementList->toArray();
> $statement = $statements[$statementList->getIndexByGuid( $guid )];

That actually does not work. You do not get a map back. I juts checked to verify this. If you got a map with guids as keys back, there'd be an issue. StatementList does not enforce uniqueness, or presence of, statements guids. So such a method would possibly filter out statements.

The way to do this now is via `StatementByGuidMap` for users that want the thing to be indexed, or to loop over the statements. As mentioned above, we could put methods that do this type of task in StatementList.

**Comment by JeroenDeDauw** [comment]
What is the problem with `addClaim`? We have `StatementList::addStatement` right?

**Comment by thiemowmde** [comment]
> constructor [...] ought to not be an issue?

Not in itself, no. It's just a hint how much code needs to be updated.

> a method that simply goes over all statements is better.

That's what I did, see https://gerrit.wikimedia.org/r/#/c/204511/.

> If you got a map with guids as keys back [...]

You must have misread my code example.

> What is the problem with addClaim?

The method is not a problem, it's the whole ClaimSummaryBuilder class.

**Comment by JeroenDeDauw** [comment]
> You must have misread my code example.

Indeed.
