### ISSUE TITLE
Add setters to `FingerprintProvider` and `StatementListProvider`

### ISSUE THREAD

**Issue by Benestar** [wmde/WikibaseDataModel#469]
#455 is already an approach to do this for the `StatementListProvider`. When we want to get rid of `Entity` we have to provide a way to set a `Fingerprint` or a `StatementList` on those providers. Currently on many places typehints refer against an `Entity` object which is apparently bad.

Instead of adding those setters to the interfaces, we could also add setters to the classes themselves (already done on `Fingerprint`, disputed for `StatementList`) or create dedicated setter interfaces which however might be too much overhead we certainly should avoid if possible.

**Comment by JeroenDeDauw** [comment]
As on the pull request:

I have some concerns here:

Current users of the interface clearly just need the getter. Adding the setter decreases the suitability of the interface for them due to less nice segregation. It might not matter in this case though. Can anyone think of a case where we'd have an implementation of this thing where we'd implement the getter though would not want to implement the setter?

* This adds mutability of the thing holding the collection itself. There might be cases where this is not desired.
* Generally Provider interfaces have no setters, so the name becomes less good

This is not a -2 or even a -1

--

I'm thinking we can solve the OCP violation that motivated this change by introducing a strategy either in this class or doing some refactoring to the changeop system and introducing one on a slightly higher level. Checking against this interface is definitely simpler for the thing we looked at. I'd not be surprised if we are forced to go with the strategy approach regardless if we want to fully fix the entity type related OCP violations in the changeop system.

--

> disputed for StatementList

Well not really - no one has stated they think this usecase is not valid or relevant enough.

**Comment by JeroenDeDauw** [comment]
This is an interesting problem though, and I wonder what the existing understanding on the subject is. In a single case where one runs into dealing with subtypes that require such different handling, using the strategy pattern is the thing to generally do. In case of Wikibase Repository, we run into this dozens of times for the same subtypes though. And having dozens of different strategies that at least partially mirror the subtypes is not nice in various ways. Doing what is proposed here allows for a simpler solution in some, definitely not all, of these cases. Does this provide sufficient worth for the risks, and is there not a better approach to begin with? I really don't know, apart from suspecting that this probably is part of the most pragmatic solution.

**Comment by Benestar** [comment]
Given the fact that a `Fingerprint` object itself is also mutable, I think we could make the `StatementList` class mutable and let the interface remain with the getter only. However, I think @thiemowmde opposed adding a remove method to that class.

But as there might not only be items and properties but also other custom entity types which contain statements, we have to find a general solution. Using strategies might be correct in general, but the api modules etc. always do the same thing so basically they must only know about the possibility so set a `StatementList` object or modify one.

What might be proposed (perhaps I will provide a patch for that), is to add a `remove` and a `clear` method to the `StatementList` class. This will keep the providers immutable and still allows us to edit `StatementList` objects. The reasons for having `StatementList` immutable are in my opinion **not** as important as the reasons to have `StatementListProvider` immutable.

**Comment by thiemowmde** [comment]
-2 for the simple reason that the interfaces are called "providers".

**Comment by thiemowmde** [comment]
I never opposed adding a `StatementList::removeStatementByGuid` for convenience, even if it is not urgently needed.

I have never seen the need for a `clear` method.

I have never seen the need for a `removeStatement( Statement $statement )` method outside of tests.

I have never seen actual numbers that justify dropping the `toArray` guarantee.

**Comment by thiemowmde** [comment]
Please use Phabricator. The team is not aware of discussions in GitHub.
